# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PJToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PJToDo
  pod 'CocoaLumberjack/Swift', '~> 3.4.2'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'ReachabilitySwift', '~> 4.1.0'
  pod 'SSZipArchive', '~> 2.1.3'
  pod 'PJPresentation', '~> 0.1.0'

  target 'PJToDoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PJToDoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
