# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'PJToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PJToDo
  pod 'CocoaLumberjack/Swift', '~> 3.8.1'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'ReachabilitySwift', '~> 4.1.0'
  pod 'SSZipArchive', '~> 2.1.3'
  pod 'PJPresentation', '~> 0.1.0'

  target 'PJToDoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PJToDoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  end

end
